# Generated by Django 4.1.2 on 2022-11-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dibujante',
            old_name='trabajos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='guionista',
            old_name='trabajos',
            new_name='apellido',
        ),
    ]
